# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 25 Jul 2022 10:23:24 +0000
*	@administrator	16
*	@ALL	0
*	@board%5fmember	16
*	@editor	16
*	@vicevaert	1
*	admin	16
*	Victor	16
*	@deputy	16
*	@subscriber	0
