# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 25 Jul 2022 10:23:24 +0000
*	@administrator	16
*	@ALL	0
*	@board%5fmember	16
*	@editor	16
*	admin	16
*	Kristoffer207	16
*	lejl002	16
*	lejl010	16
*	lejl014	16
*	lejl024	16
*	lejl207	16
*	lejl224	16
*	marie224%40akdtu%2edk	16
*	marike10%40akdtu%2edk	16
*	mathilde24%40akdtu%2edk	16
*	Victor	16
*	@vicevaert	1
